<?php
/**
 * Template Name: Privacy
 *
 * @package AnswerEngineWP
 */

get_header();
?>

<div class="page-content">
    <div class="container">
        <div class="section-label">Privacy</div>
        <h1>Privacy Policy</h1>
        <p><em>Last updated: March 5, 2026</em></p>

        <h2>What the Scanner Collects</h2>
        <p>When you use the AI Visibility Scanner, we collect:</p>
        <ul>
            <li><strong>URLs scanned:</strong> The URLs you submit for scanning are stored to generate your results page and enable sharing.</li>
            <li><strong>IP address hash:</strong> A one-way hash of your IP address is stored temporarily for rate limiting purposes (10 scans per hour). We do not store your actual IP address.</li>
            <li><strong>Scan results:</strong> The scores, sub-scores, and extraction data generated by the scanner are stored to power public score pages and PDF reports.</li>
        </ul>

        <h2>What We Don't Collect</h2>
        <ul>
            <li><strong>No cookies:</strong> We do not set cookies for tracking purposes.</li>
            <li><strong>No tracking pixels:</strong> We do not use Facebook Pixel, Google Analytics, or similar tracking technologies.</li>
            <li><strong>No personal data:</strong> We do not collect names, email addresses, or other personally identifiable information through the scanner.</li>
            <li><strong>No third-party data sharing:</strong> Scan data is not shared with or sold to third parties.</li>
        </ul>

        <h2>Analytics</h2>
        <p>We use Plausible Analytics, a privacy-focused analytics platform that does not use cookies, does not collect personal data, and is fully compliant with GDPR, CCPA, and PECR. Plausible collects aggregate traffic data only (page views, referral sources, device types). No individual visitor tracking occurs.</p>

        <h2>Data Retention</h2>
        <ul>
            <li><strong>Scan results:</strong> Stored indefinitely to support public score pages and badge verification.</li>
            <li><strong>Rate limit data:</strong> IP hashes are stored as temporary transients and automatically expire after 1 hour.</li>
            <li><strong>Cached scan data:</strong> Cached results for the same URL expire after 24 hours.</li>
        </ul>

        <h2>Data Deletion</h2>
        <p>To request deletion of a specific scan result, contact us through our <a href="<?php echo esc_url( home_url( '/support/' ) ); ?>">support page</a>. Provide the scan URL or score page link, and we will remove the data within 30 days.</p>

        <h2>WordPress Plugin</h2>
        <p>The AnswerEngineWP WordPress plugin operates entirely within your WordPress installation. It does not phone home, send data to our servers, or track your usage. All plugin functionality is local to your site.</p>

        <h2>Contact</h2>
        <p>For privacy-related questions, visit our <a href="<?php echo esc_url( home_url( '/support/' ) ); ?>">support page</a>.</p>
    </div>
</div>

<?php get_footer(); ?>
